### ISSUE TITLE
NGUIRichElementImage.cs  this script is missing!!!

### ISSUE THREAD

**Issue by HelloCSharpe** [tkokof/SimpleRichText#1]
I download this project and found this project has some error , it say :
Assets/Scripts/RichText/NGUI/Extension/NGUIRichElementAnimationImage.cs(11,50): error CS0246: The type or namespace name `NGUIRichElementImage' could not be found. Are you missing an assembly reference?
Assets/Scripts/RichText/NGUI/Extension/NGUIRichElementAnimationImage.cs(41,55): error CS0246: The type or namespace name `NGUIRichElementImageProxy' could not be found. Are you missing an assembly reference?

**Comment by tkokof** [comment]
you can import NGUI plugin and try again

**Comment by tkokof** [comment]
I've checked repo and figure it out, please update repo and try again
